object Versions {
    const val java = "1.8"
    const val compose = "1.4.0-alpha02"
    const val hilt = "2.44.2"
    const val retrofit = "2.9.0"
    const val gson = "2.10"
    const val okhttp = "4.10.0"
    const val timber = "5.0.1"
    const val lottie = "5.2.0"
    const val paging = "3.1.1"
    const val pagingCompose = "1.0.0-alpha17"
    const val lifecycleViewModel = "2.5.1"
    const val composeUi = "1.3.1"
    const val splashScreen = "1.0.0-beta02"
    const val composeActivity = "1.6.1"
    const val composeMaterial3 = "1.0.1"
    const val appCompat = "1.5.1"
    const val material = "1.8.0-beta01"
    const val composeTooling = "1.3.1"
    const val composeCompiler = "1.4.0-alpha02"
    const val lifecycle = "2.6.0-alpha03"
    const val mockk = "1.13.3"
}